spring.application.name: testClient
  #spring.cloud.loadbalancer.ribbon.enabled=false
  #CustomerContracts.ribbon.listOfServers=localhost:8093
  #ribbon.eureka.enabled=false
opentracing.jaeger.http-sender.url : http://localhost:14268/api/traces
opentracing.jaeger.log-spans : false
opentracing:
  spring:
    cloud:
      log:
        enabled: false

CustomerAccounts.feign :
  name : CustomerAccounts
  url : http://localhost:8094/CustomerAccounts
CustomerContracts.feign :
  name : CustomerContracts
  url : http://localhost:8093/CustomerContracts


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000