spring.application.name: feignclient
  #spring.cloud.loadbalancer.ribbon.enabled=false
  #CustomerContracts.ribbon.listOfServers=localhost:8093
  #ribbon.eureka.enabled=false
opentracing.jaeger.http-sender.url : http://localhost:14268/api/traces
opentracing.jaeger.log-spans : true

CustomerContractsService.feign :
  name : CustomerContracts
  url : http://localhost:8093/CustomerContracts