global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - scheme: http
    timeout: 10s
    api_version: v1
    static_configs:
    - targets: []
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: 'spring_micrometer_contracts'
  metrics_path: '/CustomerContracts/actuator/prometheus'
  scrape_interval: 5s
  static_configs:
    - targets: ['172.18.0.1:8093']
- job_name: 'spring_micrometer_account'
  metrics_path: '/CustomerAccounts/actuator/prometheus'
  scrape_interval: 5s
  static_configs:
    - targets: ['172.17.0.1:8094']	      
