server:
  servlet.context-path: /CustomerContracts
  port: 8093

spring.application.name: CustomerContractsAsync
server.tomcat.max-threads: 20

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  metrics:
    enabled: true

opentracing.jaeger.http-sender.url : http://localhost:14268/api/traces
opentracing.jaeger.log-spans : false
opentracing:
  spring:
    cloud:
      log:
        enabled: false